# Generated by Django 4.1 on 2022-08-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_eldian_alter_feeding_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='titan',
            name='eldians',
            field=models.ManyToManyField(to='main_app.eldian'),
        ),
    ]
